core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.indexview, name="home"),
    path("add/", views.addview, name="add"),
    path("delete/<int:pk>/", views.deleteview, name="delete"),
    path("all/", views.allview, name="all"),
]

imgdump/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Tag (models.Model):
    tag = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.tag

class Image (models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    pic = models.ImageField(null=True, blank=True)
    name = models.CharField(max_length=50, null=True)
    tags = models.ManyToManyField(Tag)
    public = models.BooleanField(default=True)
    def __str__(self):
        return self.name

core/forms.py
from django.forms import ModelForm
from .models import Image

class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['pic', 'name', 'public', 'tags', 'owner']
    

core/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import View, generic
from .forms import ImageForm
from core.models import Image

# Create your views here.

def indexview (request):
    if request.user.is_authenticated:
        images = Image.objects.filter(owner=request.user)
        context = {'images': images}
        return render(request, 'core/homepage.html', context)
    else:
        return HttpResponseRedirect(reverse('login'))
def addview (request):
    
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES, initial={'owner': request.user})
        if form.is_valid():
            form.save()
            print(form.cleaned_data)
            return HttpResponseRedirect(reverse('core:add'))
    else:
        form = ImageForm(initial={'owner': request.user})
    return render(request, 'core/addpage.html', {'form': form})

def deleteview (request, pk):
    Image.objects.get(id=pk).delete()
    return HttpResponseRedirect(reverse('core:home'))

def allview (request):
    images = Image.objects.all()
    context = {'images': images}
    return render(request, 'core/allview.html', context)

core/templates/core/addpage.html
{% extends 'core/index.html' %}
{% block homepage %}
<form action="{% url 'core:add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload">
</form>
{% endblock homepage %}

core/templates/core/allview.html
{% extends "core/index.html" %}
{% block homepage %}
{% if images %}
{% for image in images %}
<div class="col">
    <div class="card shadow-sm">
        <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ image.pic.url }}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ image.owner }}</small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock homepage %}

core/templates/core/homepage.html
{% extends "core/index.html" %}
{% block homepage %}
{% if images %}
{% for image in images %}
<div class="col">
    <div class="card shadow-sm">
        <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ image.pic.url }}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form action="{% url 'core:delete' image.id %}">
                    <button type="submit" class="btn btn-sm btn-outline-danger">Remove</button>
                    </form>
                </div>
                <small class="text-muted">{% for tag in image.tags.all %} #{{ tag }} {% endfor %}</small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock homepage %}

core/templates/core/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Media Bins Album</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Hello, I am Fazal Rahman, an aspiring full stack developer and this page is part of my application for an internship at Shopify. </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Social</h4>
          <ul class="list-unstyled">
            <li><a href="https://github.com/fazemahn" class="text-white">Github</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'core:home' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Media Bins</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
{% if user.is_authenticated %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-5 col-md-8 mx-auto">
        <p>
            <a href="{% url 'core:add' %}" class="btn btn-primary my-2">Add Images</a>
            <a href="{% url 'logout' %}" class="btn btn-danger my-2">Log Out</a>
            <a href="{% url 'core:all' %}" class="btn btn-secondary my-2">View All Images</a>
        </p>
      </div>
    </div>
  </section>
{% endif %}

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% block homepage %}
      {% endblock homepage %}
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
  </div>
</footer>


    <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>